package report

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/battujeevan/SentryGate-AI/validation/evidence"
	"github.com/battujeevan/SentryGate-AI/validation/f5"
)

// Phrases with fixed meaning in the report.
const (
	PhraseNotTested      = "NOT TESTED"
	PhraseUnknown        = "UNKNOWN — insufficient evidence"
	PhraseF5Prevented    = "VERIFIED — F5 prevented the tested scenario"
	PhraseF5AllowedSGBlk = "F5 allowed the tested request; SentryGate independently blocked execution."
)

// Title is the report's title.
const Title = "F5 AI Gateway — Independent Security Validation"

type writer struct{ b strings.Builder }

func (w *writer) p(format string, args ...any) { fmt.Fprintf(&w.b, format+"\n", args...) }
func (w *writer) nl()                          { w.b.WriteString("\n") }

func cell(s string) string {
	s = strings.ReplaceAll(s, "\r", "")
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.ReplaceAll(s, "|", `\|`)
}

func (w *writer) table(header []string, rows [][]string) {
	w.p("| %s |", strings.Join(header, " | "))
	seps := make([]string, len(header))
	for i := range seps {
		seps[i] = "---"
	}
	w.p("| %s |", strings.Join(seps, " | "))
	for _, r := range rows {
		cs := make([]string, len(r))
		for i, c := range r {
			cs[i] = cell(c)
		}
		w.p("| %s |", strings.Join(cs, " | "))
	}
	w.nl()
}

// Generate renders the report for the given matrix rows.
func Generate(rows []Row) string {
	w := &writer{}
	var withEvidence []Row
	for _, r := range rows {
		if r.Result != nil {
			withEvidence = append(withEvidence, r)
		}
	}
	f5Observed := false
	for _, r := range withEvidence {
		if r.F5Result != f5.ResultNotTested && r.F5Result != f5.ResultNotApplicable {
			f5Observed = true
		}
	}

	w.p("# %s", Title)
	w.nl()
	w.p("Generated by `go run ./validation/cmd/f5report` from the evidence in `validation/evidence/`. Every result below is read from an evidence file; a test without evidence is reported as %s. The report does not depend on when it is generated: the same evidence always produces the same report.", PhraseNotTested)
	w.nl()
	if !f5Observed {
		w.p("> **F5 status: %s.** No F5 component was in the request path of any test in this evidence set, and no F5 observation was recorded. This report makes no statement about how F5 AI Gateway or F5 MCP Gateway behaves. The F5 column shows what the harness observed, which is nothing.", PhraseNotTested)
		w.nl()
	}

	sectionSummary(w, rows, withEvidence, f5Observed)
	sectionScope(w)
	sectionEnvironment(w, withEvidence)
	sectionArchitecture(w, withEvidence)
	sectionMethodology(w)
	sectionSecurityModel(w)
	sectionTestCases(w, rows)
	sectionResults(w, rows)
	sectionMatrix(w, rows)
	sectionAnalysis(w, rows)
	sectionControls(w, withEvidence)
	sectionLimitations(w, rows, f5Observed)
	sectionRecommendations(w, rows, f5Observed)
	sectionEvidenceIndex(w, rows)
	sectionReproduction(w)
	return w.b.String()
}

func countBy(rows []Row, f func(Row) string) [][]string {
	m := map[string]int{}
	for _, r := range rows {
		m[f(r)]++
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	out := [][]string{}
	for _, k := range keys {
		out = append(out, []string{k, fmt.Sprint(m[k])})
	}
	return out
}

func sectionSummary(w *writer, rows, withEvidence []Row, f5Observed bool) {
	w.p("## 1. Executive Summary")
	w.nl()
	w.p("Tests defined: %d. Tests with evidence: %d.", len(rows), len(withEvidence))
	w.nl()
	if f5Observed {
		w.p("F5 observations were recorded for at least one test. F5 results per test are in section 8; each is reported exactly as classified from those observations.")
	} else {
		w.p("**F5 AI Gateway / MCP Gateway: %s.** The harness ran without F5. F5 results are %s (or NOT_APPLICABLE where a test sends no attack request through a gateway path). Nothing in this report is an F5 result.", PhraseNotTested, PhraseNotTested)
	}
	w.nl()
	w.p("What the evidence does show is the behavior of SentryGate-AI, the complementary control, and of the test infrastructure behind it:")
	w.nl()
	w.table([]string{"Matrix status", "Tests"}, countBy(rows, func(r Row) string { return r.Status }))
	w.table([]string{"SentryGate result", "Tests"}, countBy(withEvidence, func(r Row) string { return r.SentryGateResult }))
	total, expected := 0, 0
	for _, r := range withEvidence {
		if r.Result.Status != evidence.StatusBlocked {
			total += r.Result.MutationCount
			expected += r.Result.ExpectedMutations
		}
	}
	w.p("Infrastructure mutations observed across tests that ran: %d (expected by the tests' definitions: %d).", total, expected)
	w.nl()
	var failed []Row
	for _, r := range rows {
		if r.Status == evidence.StatusFailed || r.Status == evidence.StatusUnknown || r.Status == evidence.StatusBlocked {
			failed = append(failed, r)
		}
	}
	if len(failed) == 0 {
		w.p("Every test with evidence has status VERIFIED: each of its checks passed in the run that produced the evidence.")
	} else {
		w.p("Tests that are not VERIFIED (details in sections 8 and 12):")
		w.nl()
		for _, r := range failed {
			w.p("- **%s %s: %s.** %s", r.TestID, r.TestName, r.Status, firstFailure(r))
		}
	}
	w.nl()
	w.p("A VERIFIED status is a statement about the stack that was run (SentryGate-AI with the test MCP server). While the F5 result is %s it says nothing about F5.", PhraseNotTested)
	w.nl()
}

func firstFailure(r Row) string {
	if r.Result == nil {
		return "No evidence."
	}
	if r.Result.BlockedReason != "" {
		return "Blocked: " + r.Result.BlockedReason
	}
	var parts []string
	for _, c := range r.Result.Checks {
		if c.Result != evidence.CheckPass {
			parts = append(parts, fmt.Sprintf("%s (expected %s; observed %s)", c.Name, c.Expected, c.Observed))
		}
	}
	if len(parts) == 0 {
		return r.Notes
	}
	return "Not passed: " + strings.Join(parts, "; ") + "."
}

func sectionScope(w *writer) {
	w.p("## 2. Scope")
	w.nl()
	w.p("**System under test:** F5 AI Gateway / F5 MCP Gateway, as the authorization layer between an AI agent and the tools it calls.")
	w.nl()
	w.p("**Complementary control:** SentryGate-AI, an independent execution-boundary control. It is not a replacement for F5 and is not evaluated as one; it is present so that each test can show, separately, what the gateway decided, what SentryGate decided, and what actually happened to the infrastructure.")
	w.nl()
	w.p("**In scope:** the authorization-to-execution path for MCP tool calls: whether an operation that was authorized is the operation that executes, executes at most once, executes only under current policy, and executes only for the authenticated identity. Twelve scenarios (TC01-TC12) cover legitimate use, substitution of tool, target, arguments and identity, replay, concurrency, workflow reset, lost responses, forged authorizations and privilege escalation.")
	w.nl()
	w.p("**Out of scope:** prompt-injection and content inspection, model behavior, F5 features other than authorization of tool calls, performance, availability, and any production deployment. The agent is deterministic (no LLM).")
	w.nl()
}

func sectionEnvironment(w *writer, withEvidence []Row) {
	w.p("## 3. Tested Environment")
	w.nl()
	if len(withEvidence) == 0 {
		w.p("%s: no evidence, so no environment was recorded.", PhraseNotTested)
		w.nl()
		return
	}
	groups := map[string][]string{}
	envs := map[string]map[string]any{}
	for _, r := range withEvidence {
		key := fmt.Sprint(sortedPairs(r.Result.Environment))
		groups[key] = append(groups[key], r.TestID)
		envs[key] = r.Result.Environment
	}
	keys := make([]string, 0, len(groups))
	for k := range groups {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		w.p("Recorded in the evidence of %s:", strings.Join(groups[k], ", "))
		w.nl()
		var rows [][]string
		for _, kv := range sortedPairs(envs[k]) {
			rows = append(rows, []string{kv[0], kv[1]})
		}
		w.table([]string{"Property", "Value"}, rows)
	}
	w.p("F5 components present: **none**. The harness neither starts nor simulates any F5 component.")
	w.nl()
}

func sortedPairs(m map[string]any) [][2]string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	out := make([][2]string, 0, len(keys))
	for _, k := range keys {
		out = append(out, [2]string{k, fmt.Sprint(m[k])})
	}
	return out
}

func sectionArchitecture(w *writer, withEvidence []Row) {
	w.p("## 4. Architecture")
	w.nl()
	w.p("Each test runs against its own stack: a SentryGate proxy, a SentryGate worker configured with the MCP adapter, and a test MCP server with a fresh SQLite database, all as separate processes. A single Temporal dev server is shared, with a separate task queue per test.")
	w.nl()
	w.p("```text")
	w.p("deterministic test agent")
	w.p("   |  path \"gateway\": POST /v1/intercept with the agent's API key")
	w.p("   v")
	w.p("[gateway insertion point A: F5 AI Gateway in front of ingress - NOT PRESENT]")
	w.p("   v")
	w.p("SentryGate proxy: authenticate, evaluate policy, record decision, start workflow")
	w.p("   v")
	w.p("Temporal  <---  path \"execution-boundary\": attacker starts / terminates / resets workflows directly")
	w.p("   v")
	w.p("SentryGate worker: ingress binding -> execution claim -> re-validation -> execution fence -> MCP adapter")
	w.p("   v")
	w.p("[gateway insertion point B: F5 MCP Gateway in front of the MCP server - NOT PRESENT]")
	w.p("   v")
	w.p("test MCP server: read/update/export/delete_customer; records every tools/call; never deduplicates")
	w.p("```")
	w.nl()
	if len(withEvidence) > 0 {
		env := withEvidence[0].Result.Environment
		w.p("Paths recorded in the evidence: ingress `%v`; worker to MCP `%v`.", env["ingress_path"], env["worker_mcp_path"])
		w.nl()
	}
	w.p("Three layers are compared in every test:")
	w.nl()
	w.p("1. **F5** (layer 1): the authorization decision F5 recorded for each gateway-path request, obtained through the `F5ObservationProvider` interface. With the mock provider every field is `MOCK` and the decision is `NOT_OBSERVED`.")
	w.p("2. **SentryGate** (layer 2): the ingress decision, workflow re-validation, execution claim, fence, dispatch, reconciliation and final run outcome, read from SentryGate's audit store and Temporal history.")
	w.p("3. **Infrastructure** (layer 3): every tools/call the test MCP server received and the rows it changed. The mutation count is the key metric: it shows whether an operation happened 0, 1 or more times regardless of what either control reported.")
	w.nl()
}

func sectionMethodology(w *writer) {
	w.p("## 5. Methodology")
	w.nl()
	w.p("- Every test starts a fresh stack, records the MCP database before the test, sends the requests the test defines, waits for every workflow run it started to close, and records the database afterwards.")
	w.p("- Requests take one of two paths. **gateway**: an HTTP request to SentryGate ingress, the path an agent uses and the one a gateway sits on. **execution-boundary**: direct Temporal API calls, modelling an attacker who can reach the workflow engine and presents a modified, replayed or forged authorization there.")
	w.p("- Each request has a role. Legitimate requests set up an authorization; attack requests are the scenario under test. The F5 and SentryGate layer results of an attack test are computed over its attack requests.")
	w.p("- Each test defines its checks before it runs: the SentryGate outcome expected for each request, specific state checks, and two infrastructure checks applied to every test: the mutation count equals the test's expected count, and no idempotency key mutated the target more than once.")
	w.p("- API keys are generated per stack and are never written to evidence.")
	w.nl()
	w.p("**Matrix status** (column `status`):")
	w.nl()
	w.table([]string{"Status", "Meaning"}, [][]string{
		{evidence.StatusVerified, "The test ran and every check passed. Describes the stack that was run; not an F5 result unless the F5 column is."},
		{evidence.StatusFailed, "The test ran and at least one check failed."},
		{evidence.StatusBlocked, "The test could not be carried out (environment or harness problem). Its checks say nothing about the system."},
		{evidence.StatusNotTested, "No evidence exists for the test."},
		{evidence.StatusUnknown, "The test ran but the evidence is insufficient or inconsistent."},
		{evidence.StatusNotApplicable, "The test does not apply."},
	})
	w.p("**F5 result** (column `f5_result`), and the wording used for it:")
	w.nl()
	w.table([]string{"f5_result", "Report wording", "When"}, [][]string{
		{f5.ResultNotTested, PhraseNotTested, "Any relevant observation did not come from F5 (for example the mock provider). This is the result whenever F5 is not in the path."},
		{f5.ResultNotApplicable, "NOT APPLICABLE", "The test sends no request of the relevant role through a gateway path."},
		{f5.ResultUnknown, PhraseUnknown, "Real F5 observations exist but at least one has no ALLOW or DENY decision."},
		{f5.ResultPrevented, PhraseF5Prevented, "Attack test: F5 denied every attack request, according to real F5 observations."},
		{f5.ResultAllowed, PhraseF5AllowedSGBlk, "Attack test: F5 allowed an attack request and SentryGate refused every attack request. If SentryGate did not, the report states what executed and does not call it a vulnerability."},
	})
	w.p("An F5 result is never inferred from SentryGate's behavior, and SentryGate's behavior is never attributed to F5.")
	w.nl()
}

func sectionSecurityModel(w *writer) {
	w.p("## 6. Security Model")
	w.nl()
	w.p("**Assets:** customer records in the test MCP server (read, modify, export, delete).")
	w.nl()
	w.p("**Actors:** an authorized agent (agent-a: read and update); a read-only agent (agent-b); an attacker without valid agent credentials; an attacker with access to the workflow engine (Temporal) but not to agent keys.")
	w.nl()
	w.p("**Properties tested:**")
	w.nl()
	w.table([]string{"Property", "Statement", "Tests"}, [][]string{
		{"Authorization binding", "The tool, target, arguments and identity executed are those authorized.", "TC02, TC03, TC04, TC11, TC12"},
		{"At most once", "One authorization executes at most once, under replay, concurrency and workflow reset.", "TC06, TC07, TC08"},
		{"Policy currency", "Execution happens only if the policy in force at execution still permits it.", "TC05"},
		{"Genuine authorization", "Execution requires an ALLOW decision recorded by ingress.", "TC10"},
		{"Unknown outcomes", "An operation whose outcome is unknown is reconciled, never blindly retried.", "TC09"},
		{"Baseline", "Legitimate operations execute exactly once.", "TC01"},
	})
}

func sectionTestCases(w *writer, rows []Row) {
	w.p("## 7. Test Cases")
	w.nl()
	for _, r := range rows {
		w.p("### %s %s", r.TestID, r.TestName)
		w.nl()
		if r.Result == nil {
			w.p("%s: no evidence; the definition is in `validation/cases/tc.go`.", PhraseNotTested)
			w.nl()
			continue
		}
		w.p("- **Kind:** %s", r.Result.Kind)
		w.p("- **Objective:** %s", r.Result.Objective)
		w.p("- **Method:**")
		for i, m := range r.Result.Method {
			w.p("  %d. %s", i+1, m)
		}
		w.p("- **Expected:** %s", r.Result.Expected)
		w.p("- **Expected infrastructure mutations:** %d", r.Result.ExpectedMutations)
		w.nl()
	}
}

func f5Wording(r Row) string {
	if r.Result == nil {
		return PhraseNotTested
	}
	switch r.F5Result {
	case f5.ResultNotTested:
		return PhraseNotTested + " — no F5 component was in the request path; no F5 behavior was observed."
	case f5.ResultNotApplicable:
		return "NOT APPLICABLE — the attack requests in this test go directly to the execution boundary and pass through no gateway in front of ingress."
	case f5.ResultUnknown:
		return PhraseUnknown
	case f5.ResultPrevented:
		if r.Result.Kind == evidence.KindAttack {
			return PhraseF5Prevented
		}
		return "F5 denied a legitimate request in this test. This is an observation of the tested configuration, not a finding by itself."
	case f5.ResultAllowed:
		if r.Result.Kind != evidence.KindAttack {
			return "F5 allowed the legitimate request(s), as expected."
		}
		switch r.SentryGateResult {
		case evidence.SGBlocked:
			return PhraseF5AllowedSGBlk
		case evidence.SGDidNotBlock:
			return "F5 allowed the tested request and SentryGate did not block execution. This records what was observed in the tested configuration; it is not a vulnerability finding unless a reproducible security defect is demonstrated and analysed."
		}
		return "F5 allowed the tested request; SentryGate result: " + r.SentryGateResult + "."
	}
	return PhraseUnknown
}

func sgWording(r Row) string {
	res := r.Result
	switch r.SentryGateResult {
	case evidence.SGBlocked:
		return "SentryGate refused every attack request in this test."
	case evidence.SGDidNotBlock:
		var labels []string
		for _, a := range res.Attempts {
			if a.Role == "attack" && a.SentryGate == "EXECUTED" {
				labels = append(labels, "\""+a.Label+"\"")
			}
		}
		return "At least one attack request executed: " + strings.Join(labels, ", ") + "."
	case evidence.SGExecuted:
		return "SentryGate allowed and executed the legitimate request(s)."
	case evidence.SGNotExecuted:
		return "The legitimate request(s) did not execute."
	case evidence.SGNotApplicable:
		return "No request of the relevant role."
	}
	return PhraseUnknown
}

func sectionResults(w *writer, rows []Row) {
	w.p("## 8. Results")
	w.nl()
	for _, r := range rows {
		w.p("### %s %s: %s", r.TestID, r.TestName, r.Status)
		w.nl()
		if r.Result == nil {
			w.p("%s. No evidence.", PhraseNotTested)
			w.nl()
			continue
		}
		res := r.Result
		if res.BlockedReason != "" {
			w.p("**BLOCKED:** %s", res.BlockedReason)
			w.nl()
		}
		w.p("- **F5 (layer 1):** `%s`. %s", r.F5Result, f5Wording(r))
		w.p("- **SentryGate (layer 2):** `%s`. %s", r.SentryGateResult, sgWording(r))
		w.p("- **Infrastructure (layer 3):** `%s`: %d tools/call invocation(s), %d mutation(s), expected %d.", r.InfrastructureResult, res.Invocations, res.MutationCount, res.ExpectedMutations)
		w.p("- **Run:** %s to %s. Evidence: `%s`.", res.StartedAt, res.FinishedAt, res.EvidencePath)
		w.nl()
		if len(res.Attempts) > 0 {
			var tr [][]string
			for _, a := range res.Attempts {
				f5d := a.F5Decision
				if f5d == "" {
					f5d = "-"
				} else {
					f5d += " (" + a.F5Source + ")"
				}
				tt := "-"
				if a.Tool != "" {
					tt = a.Tool + " / " + a.Target
				}
				tr = append(tr, []string{a.Label, a.Role, a.Path, a.AgentID, tt, f5d, strings.TrimSpace(a.SentryGate + " " + a.SentryGateDetail)})
			}
			w.table([]string{"Request", "Role", "Path", "Agent", "Tool / target", "F5 decision (source)", "SentryGate outcome"}, tr)
		}
		if len(res.Checks) > 0 {
			var cr [][]string
			for _, c := range res.Checks {
				cr = append(cr, []string{c.Name, c.Expected, c.Observed, c.Result})
			}
			w.table([]string{"Check", "Expected", "Observed", "Result"}, cr)
		}
		for _, n := range res.Notes {
			w.p("- Note: %s", n)
		}
		if len(res.Notes) > 0 {
			w.nl()
		}
	}
}

func sectionMatrix(w *writer, rows []Row) {
	w.p("## 9. Validation Matrix")
	w.nl()
	w.p("Also written to `validation/results/validation-matrix.csv` (same rows; the CSV `notes` column has the full notes).")
	w.nl()
	var tr [][]string
	for _, r := range rows {
		tr = append(tr, []string{r.TestID, r.TestName, r.F5Result, r.SentryGateResult, r.InfrastructureResult, r.MutationCount, r.EvidencePath, r.Status})
	}
	w.table([]string{"test_id", "test_name", "f5_result", "sentrygate_result", "infrastructure_result", "mutation_count", "evidence_path", "status"}, tr)
}

var codePattern = regexp.MustCompile(`\b[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+\b`)

func sectionAnalysis(w *writer, rows []Row) {
	w.p("## 10. Authorization-to-Execution Analysis")
	w.nl()
	w.p("For each test: what layer 1 decided, what layer 2 decided, and what layer 3 shows actually happened.")
	w.nl()
	var tr [][]string
	for _, r := range rows {
		if r.Result == nil {
			tr = append(tr, []string{r.TestID, PhraseNotTested, PhraseNotTested, PhraseNotTested, "-"})
			continue
		}
		match := "matches"
		if r.Result.MutationCount != r.Result.ExpectedMutations {
			match = "DIFFERS"
		}
		if r.Result.Status == evidence.StatusBlocked {
			match = "not measured (BLOCKED)"
		}
		tr = append(tr, []string{r.TestID, r.F5Result, r.SentryGateResult,
			fmt.Sprintf("%d mutation(s), expected %d", r.Result.MutationCount, r.Result.ExpectedMutations), match})
	}
	w.table([]string{"Test", "Layer 1: F5", "Layer 2: SentryGate", "Layer 3: infrastructure", "Layer 3 vs expectation"}, tr)

	type key struct{ outcome, code string }
	counts := map[key]int{}
	tests := map[key]map[string]bool{}
	for _, r := range rows {
		if r.Result == nil {
			continue
		}
		for _, a := range r.Result.Attempts {
			if a.Role != "attack" {
				continue
			}
			codes := codePattern.FindAllString(a.SentryGateDetail, -1)
			if len(codes) == 0 {
				codes = []string{"-"}
			}
			for _, c := range uniq(codes) {
				k := key{a.SentryGate, c}
				counts[k]++
				if tests[k] == nil {
					tests[k] = map[string]bool{}
				}
				tests[k][r.TestID] = true
			}
		}
	}
	keys := make([]key, 0, len(counts))
	for k := range counts {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].outcome != keys[j].outcome {
			return keys[i].outcome < keys[j].outcome
		}
		return keys[i].code < keys[j].code
	})
	if len(keys) > 0 {
		w.p("Where attack requests stopped (or did not), by SentryGate outcome and the codes in its detail:")
		w.nl()
		var cr [][]string
		for _, k := range keys {
			cr = append(cr, []string{k.outcome, k.code, fmt.Sprint(counts[k]), strings.Join(sortedKeys(tests[k]), ", ")})
		}
		w.table([]string{"SentryGate outcome", "Code", "Attack requests", "Tests"}, cr)
	}
	w.p("While F5 is %s, the layer 1 column carries no information, and the agreement between layers 2 and 3 above is a property of SentryGate and the test infrastructure only.", PhraseNotTested)
	w.nl()
}

func uniq(s []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, x := range s {
		if !seen[x] {
			seen[x] = true
			out = append(out, x)
		}
	}
	return out
}

func sortedKeys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

type control struct {
	name, checks, code string
	match              func(a evidence.AttemptSummary) bool
	matchCheck         func(c evidence.Check) bool
}

func sectionControls(w *writer, withEvidence []Row) {
	w.p("## 11. SentryGate-AI Complementary Controls")
	w.nl()
	w.p("Controls of SentryGate-AI that acted in this evidence set. A control is listed against a test only if that test's evidence shows it refusing a request or passing a check; a control with no such evidence shows \"no evidence in this set\".")
	w.nl()
	controls := []control{
		{name: "Ingress authentication", checks: "API key identifies the agent; missing or unknown keys are refused", code: "internal/auth",
			match: func(a evidence.AttemptSummary) bool {
				return a.SentryGate == "REJECTED_AT_INGRESS" && strings.Contains(a.SentryGateDetail, "HTTP 401")
			}},
		{name: "Strict request decoding", checks: "unknown fields (such as a claimed agent_id) are refused", code: "cmd/sentrygate/handler.go",
			match: func(a evidence.AttemptSummary) bool {
				return a.SentryGate == "REJECTED_AT_INGRESS" && strings.Contains(a.SentryGateDetail, "HTTP 400")
			}},
		{name: "Ingress policy evaluation", checks: "agent, command, target, environment", code: "internal/decision/evaluate.go",
			match: func(a evidence.AttemptSummary) bool { return a.SentryGate == "DENIED_AT_INGRESS" }},
		{name: "One open workflow per proposal", checks: "a second request for a running proposal is not executed (409)", code: "cmd/sentrygate/handler.go",
			match: func(a evidence.AttemptSummary) bool {
				return a.SentryGate == "NOT_STARTED" && strings.Contains(a.SentryGateDetail, "HTTP 409")
			}},
		{name: "Ingress decision binding", checks: "decision exists, is INGRESS, is ALLOW, same agent, same recomputed request hash, same proposal and workflow ID", code: "internal/decision/ingress.go",
			match: func(a evidence.AttemptSummary) bool {
				return strings.Contains(a.SentryGateDetail, "INGRESS_DECISION_INVALID")
			}},
		{name: "Execution claim and fence", checks: "one decision, one execution; the adapter is called only by the run that moves the claim to EXECUTING", code: "workflows/saga.go, workflows/activities.go, internal/audit/claims.go",
			match: func(a evidence.AttemptSummary) bool {
				return strings.Contains(a.SentryGateDetail, "EXECUTION_CLAIM_REJECTED")
			},
			matchCheck: func(c evidence.Check) bool {
				return strings.HasPrefix(c.Name, "fence result") && c.Result == evidence.CheckPass
			}},
		{name: "Re-validation against current policy", checks: "the worker re-evaluates the proposal under the policy it has loaded", code: "workflows/decisions.go",
			match: func(a evidence.AttemptSummary) bool {
				return strings.Contains(a.SentryGateDetail, "REVALIDATION_DENIED")
			}},
		{name: "MCP adapter target guard", checks: "arguments may not set the MCP target argument; the authorized target is always the one sent", code: "workflows/mcp_adapter.go",
			match: func(a evidence.AttemptSummary) bool { return a.SentryGate == "REFUSED_BY_ADAPTER" }},
		{name: "Unknown-outcome reconciliation", checks: "UNKNOWN dispatch moves the claim to RECONCILIATION_REQUIRED and asks the target for the outcome; no re-send", code: "workflows/saga.go, workflows/mcp_adapter.go",
			matchCheck: func(c evidence.Check) bool { return c.Name == "reconciliation" && c.Result == evidence.CheckPass }},
	}
	var tr [][]string
	for _, c := range controls {
		set := map[string]bool{}
		for _, r := range withEvidence {
			for _, a := range r.Result.Attempts {
				if c.match != nil && a.Role == "attack" && c.match(a) {
					set[r.TestID] = true
				}
			}
			for _, ch := range r.Result.Checks {
				if c.matchCheck != nil && c.matchCheck(ch) {
					set[r.TestID] = true
				}
			}
		}
		where := "no evidence in this set"
		if len(set) > 0 {
			where = strings.Join(sortedKeys(set), ", ")
		}
		tr = append(tr, []string{c.name, c.checks, c.code, where})
	}
	w.table([]string{"Control", "What it checks", "Code", "Acted in"}, tr)
	w.p("These controls complement a gateway; they do not replace one. They act at the execution boundary, after any gateway decision, and are designed to hold even when a request reaches the workflow engine without passing through ingress.")
	w.nl()
}

func sectionLimitations(w *writer, rows []Row, f5Observed bool) {
	w.p("## 12. Limitations")
	w.nl()
	if !f5Observed {
		w.p("- **No F5 component was tested.** Every F5 result is %s or NOT_APPLICABLE. The harness has an F5 observation boundary (`validation/f5`) but no provider for a real F5 deployment yet.", PhraseNotTested)
	}
	w.p("- The infrastructure is a test MCP server with a disposable SQLite database, not a production system. Its status tool (`sentrygate_execution_status`) exists so reconciliation can be exercised; production MCP servers may offer nothing equivalent.")
	w.p("- The agent is deterministic and sends exactly the requests each test defines. No LLM, prompt or content-level behavior is tested.")
	w.p("- Temporal runs as the CLI dev server (in-memory, single process). Clustered deployments, persistence failures and network partitions are not tested.")
	w.p("- Each test is one run. Timing-dependent behavior (concurrency, reset during dispatch) was observed in that run; a single run does not prove it under all interleavings.")
	w.p("- Process stops are abrupt kills (the harness cannot send a graceful signal on every platform).")
	seen := map[string]bool{}
	for _, r := range rows {
		if r.Result == nil {
			continue
		}
		for _, l := range r.Result.Limitations {
			if !seen[l] {
				seen[l] = true
				w.p("- %s (%s)", l, r.TestID)
			}
		}
	}
	var missing []string
	for _, r := range rows {
		if r.Result == nil {
			missing = append(missing, r.TestID)
		}
	}
	if len(missing) > 0 {
		w.p("- No evidence for %s; those tests are %s.", strings.Join(missing, ", "), PhraseNotTested)
	}
	w.nl()
}

// recommendation is shown for a test only when its evidence contains the
// failed check (by name prefix) or the note (by substring) it is about.
type recommendation struct {
	testID, failedCheck, note, text string
}

var recommendations = []recommendation{
	{testID: "TC06", failedCheck: "SentryGate outcome: agent-a re-sends the identical HTTP request",
		text: "Request replay: the evidence shows a re-sent request executing again after its first workflow closed (behavior documented in INTEGRATION.md). If at-most-once per request is required, add request-level replay protection at ingress, for example by refusing a proposal ID that already has a completed execution."},
	{testID: "TC07", failedCheck: "SentryGate outcome: present the ALLOW recorded for 409 response",
		text: "Unused ALLOW decisions: ingress records an ALLOW decision before it starts the workflow, so a request answered 409 leaves an ALLOW that was never executed. The evidence shows such a decision being accepted at the execution boundary. Consider recording that the decision's workflow was not started, and refusing it at ingress binding, so that it cannot be presented later."},
	{testID: "TC08", note: "After the in-flight reset, the claim is EXECUTING and owned by the terminated original run",
		text: "Reset during dispatch: the claim stays EXECUTING under a terminated run and no run is left to complete or reconcile it. Consider detecting claims whose owner run has closed and reconciling them through the adapter."},
}

func sectionRecommendations(w *writer, rows []Row, f5Observed bool) {
	w.p("## 13. Recommendations")
	w.nl()
	if !f5Observed {
		w.p("**To obtain F5 results:**")
		w.nl()
		w.p("1. Deploy F5 AI Gateway and/or F5 MCP Gateway at insertion point A (in front of SentryGate ingress, `-ingress-url`) and/or B (in front of the test MCP server, `-worker-mcp-url`, with `-mcp-listen` fixing the test server's address).")
		w.p("2. Implement `f5.F5ObservationProvider` against F5's documented audit or logging interface, populating every field from real F5 records and leaving `MockedFields` empty.")
		w.p("3. Re-run `go run ./validation/cmd/f5validate -tc all -f5-provider <provider>` and regenerate this report. Only then can an F5 result other than %s appear.", PhraseNotTested)
		w.nl()
	}
	var recs []string
	for _, r := range rows {
		if r.Result == nil {
			continue
		}
		covered := false
		for _, rec := range recommendations {
			if rec.testID == r.TestID && applies(rec, r.Result) {
				recs = append(recs, fmt.Sprintf("- **%s (SentryGate-AI):** %s", r.TestID, rec.text))
				covered = true
			}
		}
		if r.Status == evidence.StatusFailed && !covered {
			recs = append(recs, fmt.Sprintf("- **%s:** investigate the failed checks in section 8 before relying on the control this test covers.", r.TestID))
		}
	}
	for _, r := range rows {
		if r.Status == evidence.StatusBlocked {
			recs = append(recs, fmt.Sprintf("- **%s:** BLOCKED; resolve the environment problem (%s) and re-run.", r.TestID, r.Result.BlockedReason))
		}
	}
	if len(recs) > 0 {
		w.p("**From the evidence:**")
		w.nl()
		for _, r := range recs {
			w.p("%s", r)
		}
		w.nl()
	}
}

func applies(rec recommendation, res *evidence.Result) bool {
	if rec.failedCheck != "" {
		for _, c := range res.Checks {
			if c.Result == evidence.CheckFail && strings.HasPrefix(c.Name, rec.failedCheck) {
				return true
			}
		}
	}
	if rec.note != "" {
		for _, n := range res.Notes {
			if strings.Contains(n, rec.note) {
				return true
			}
		}
	}
	return false
}

func sectionEvidenceIndex(w *writer, rows []Row) {
	w.p("## 14. Evidence Index")
	w.nl()
	var tr [][]string
	for _, r := range rows {
		if r.Result == nil {
			tr = append(tr, []string{r.TestID, "-", "-", PhraseNotTested})
			continue
		}
		missing := "none"
		if len(r.MissingFiles) > 0 {
			missing = strings.Join(r.MissingFiles, ", ")
		}
		tr = append(tr, []string{r.TestID, "`" + r.EvidencePath + "`", strings.Join(r.Result.Files, ", "), missing})
	}
	w.table([]string{"Test", "Directory", "Files", "Missing required files"}, tr)
	w.p("Required files per test: %s.", strings.Join(evidence.RequiredFiles, ", "))
	w.nl()
}

func sectionReproduction(w *writer) {
	w.p("## 15. Reproduction Instructions")
	w.nl()
	w.p("Prerequisites: Go (the version in `go.mod`) and network access the first time, to download the Temporal CLI used as the dev server (or set `TEMPORAL_CLI_PATH`). No Docker, no F5.")
	w.nl()
	w.p("```sh")
	w.p("make validation-f5            # all tests, then this report")
	w.p("make validation-f5-tc05       # one test (any of tc01..tc12)")
	w.p("make validation-report        # this report, from stored evidence only")
	w.p("```")
	w.nl()
	w.p("Without make:")
	w.nl()
	w.p("```sh")
	w.p("go run ./validation/cmd/f5validate -tc all")
	w.p("go run ./validation/cmd/f5validate -tc TC05")
	w.p("go run ./validation/cmd/f5report")
	w.p("```")
	w.nl()
	w.p("See `validation/F5/README.md` for how to place F5 in the path and connect a real observation provider.")
}
